Regenerated new workload ARM template and added missing module param
Azure/missionlz pull request #502
Opened 2021-11-04 19:22 UTC by brooke-hamilton

# Description

Regenerated the ARM template from the Bicep template. Also fixed an issue in which the `spokeType` parameter was not being supplied for the `workloadVirtualNetworkPeerings` module.

## Issue reference

The issue this PR will close: #501

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

2021-11-04 19:25 UTC, brooke-hamilton commented
@glennmusa please verify that using `workloadName` is the right value to use for the `spokeType` parameter. A 'type' and a 'name' are not always the same thing, but in this case I think we should use the workload name as the spoke type so that we can support unique and multiple workload names. Or maybe I'm wrong and all new workloads should use the same value for `spokeType`.

2021-11-05 13:59 UTC, glennmusa commented
> @glennmusa please verify that using `workloadName` is the right value to use for the `spokeType` parameter. A 'type' and a 'name' are not always the same thing, but in this case I think we should use the workload name as the spoke type so that we can support unique and multiple workload names. Or maybe I'm wrong and all new workloads should use the same value for `spokeType`.

I think you're right that a `type` and a `name` are not the same thing. This looks like a miss on my part. 

In fact, the spoke `type` I created in the root module does use a `name` property and not a `type` property:

https://github.com/Azure/missionlz/blob/b39c93062058ed7c6b69176f3e1188b99b2c724f/src/bicep/mlz.bicep#L557-L559

I think the right thing to do here would be to rename the `spokeType` property to `spokeName` in the `spokeNetworkPeering` module to reflect that:

https://github.com/Azure/missionlz/blob/b39c93062058ed7c6b69176f3e1188b99b2c724f/src/bicep/modules/spokeNetworkPeering.bicep#L3

Good catch! Happy to pair up on the change if it bubbles up unwieldly.

2021-11-05 14:00 UTC, glennmusa requested changes
Agree on your changes for `spokeType` => `spokeName`

2021-11-05 21:36 UTC, brooke-hamilton commented
> Agree on your changes for `spokeType` => `spokeName`

Done. Please re-review. 💯

2021-11-08 16:31 UTC, glennmusa approved these changes
🎉

2021-11-08 16:31 UTC, merged