Check that Portal UI form outputs map to template parameter inputs on pull requests
Azure/missionlz pull request #620
Opened 2022-01-25 17:28 UTC by glennmusa

# Description

So that:

- On a PR, check to see that the Portal UI is compatible with the compiled Bicep deployment template
- check that all required parameters in the deployment template have a matching named output in the Portal UI template
- check that the Portal UI template outputs contain only named values that are available parameters in the deployment template

Here's what it looks like when this check fails:

https://ag-ascii.visualstudio.com/Mission%20Landing%20Zone%20-%20Pipeline/_build/results?buildId=6746&view=results

Here's what it looks like when this check passes:

https://ag-ascii.visualstudio.com/Mission%20Landing%20Zone%20-%20Pipeline/_build/results?buildId=6756&view=results

These proposed changes:

- adds an Azure DevOps Pipeline that executes on pull requests to `/main`
- when the pipeline executes, the `mlz.portal.json` declarative form and `mlz.json` deployment template are validated and if any errors occur, the pipeline fails
- references an external utility to perform the validation from [glennmusa/validate-declarative-form](https://github.com/glennmusa/validate-declarative-form)

## Issue reference

The issue this PR will close: #598

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

2022-02-01 21:01 UTC, brooke-hamilton requested changes
This PR is 🚀 🦖 🎉 . The README was easy to follow and I was able to reproduce everything documented there, including testing mismatched form and parameters. I had one issue with building the dev container, but I added a suggestion to fix it. 

If you think this is a general purpose tool, in the future it could move to https://github.com/glennmusa and we could reference it there.

2022-02-02 15:36 UTC, glennmusa commented
> This PR is 🚀 🦖 🎉 . The README was easy to follow and I was able to reproduce everything documented there, including testing mismatched form and parameters. I had one issue with building the dev container, but I added a suggestion to fix it.
> 
> If you think this is a general purpose tool, in the future it could move to https://github.com/glennmusa and we could reference it there.

I like your idea to make use of this as a general purpose tool from a different repository:

1. this tool is not MLZ-specific
1. this tool should be superseded in time by an official product 

I'll update this branch so that it makes use of the tool in a pipeline, but host that tool elsewhere. Thanks for the idea.

2022-02-02 21:28 UTC, glennmusa commented on .vscode/extensions.json
> +		"ms-python.vscode-pylance"
Thanks for the thorough review, I've taken your suggestions here: https://github.com/glennmusa/validate-declarative-form/blob/530e329a7056518818388bccacd8097a7ed2c408/.devcontainer/devcontainer.json#L18-L43

2022-02-02 21:30 UTC, glennmusa commented on src/bicep/form/validation/README.md
> +So, execute it like:
OBE -- moved this tool to its own repo: https://github.com/glennmusa/validate-declarative-form

2022-02-02 21:31 UTC, glennmusa commented on src/bicep/form/validation/README.md
> +python -m unittest validate_declarative_form_test.py -v
Thanks for the thorough review, I've taken your suggestions here: https://github.com/glennmusa/validate-declarative-form/blob/530e329a7056518818388bccacd8097a7ed2c408/README.md?plain=1#L88-L91

2022-02-02 21:31 UTC, glennmusa commented on src/bicep/form/validation/validate_declarative_form.py
> +    except Exception as exception:
Thank you for the thorough review, I took your feedback and implemented it here: https://github.com/glennmusa/validate-declarative-form/blob/530e329a7056518818388bccacd8097a7ed2c408/validate_declarative_form.py#L126

2022-02-02 21:33 UTC, glennmusa commented on .vscode/settings.json
> +    "python.testing.unittestEnabled": true
This brings up another issue of housekeeping we can do within the repository. Push the team and contributors into using the devcontainer so we don't maintain these two separate and LIFO settings configurations.

2022-02-02 21:35 UTC, glennmusa commented
Thanks for the thorough review @brooke-hamilton!

I've taken your advice and now host this tool here: https://github.com/glennmusa/validate-declarative-form

It's extremely lightweight today to `cURL` the single utility this change needs, but for completeness, I added an Issue in that backlog to expose the utility as a GitHub Action: https://github.com/glennmusa/validate-declarative-form/issues/4

2022-02-02 22:37 UTC, brooke-hamilton approved these changes

2022-02-02 23:41 UTC, merged